name: Lint & Validate

on:
  pull_request_target:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint & Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: |
          yarn run lint

      - name: Validate
        run: |
          yarn run validate
