name: Lint & Validate

on:
  pull_request_target:
    branches:
      - main
    paths-ignore:
      - "src/technologies/*.json"
      - "src/categories.json"
      - "src/groups.json"
      - "src/images/icons/**"

jobs:
  lint:
    name: Lint & Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Install dependencies
        run: yarn install

      - name: Lint and Validate
        run: |
          yarn run lint
          yarn run validate
