name: Upload technologies to BQ

on:
  push:
    branches:
      - main
    paths:
      - "src/technologies/*.json"
      - "src/categories.json"
      - "src/groups.json"
      - "src/images/icons/**"
  workflow_dispatch:

jobs:
  test:
    name: Test and upload to GCP
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn install

      - name: Validate
        run: yarn run validate

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            tech:
              - src/technologies/*.json
              - src/technologies/*.json
              - src/categories.json
              - src/groups.json
            icons:
              - src/images/icons/**

      - name: Upload technology rules to BigQuery
        if: steps.changed-files.outputs.tech_any_changed == 'true'
        env:
          GCP_PROJECT_ID: 'httparchive'
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: yarn run tech_upload

      - name: Convert changed icons
        if: steps.changed-files.outputs.icons_any_changed == 'true'
        env:
          CHANGED_ICONS: ${{ steps.changed-files.outputs.icons_all_changed_files }}
        run: yarn run icons_convert

      - if: steps.changed-files.outputs.icons_any_changed == 'true'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - if: steps.changed-files.outputs.icons_any_changed == 'true'
        uses: google-github-actions/setup-gcloud@v2

      - name: Upload icons to Cloud Storage
        if: steps.changed-files.outputs.icons_any_changed == 'true'
        run: yarn run icons_upload
